### ISSUE TITLE
Blocked accessing for cross-origin Content.

### ISSUE THREAD

**Issue by akshay-bhavsar** [KingsOnline/adapt-social#1]
Blocked accessing for cross-origin Content.

### Your environment
* version (AT/Framework): 4.0.0
* which browser and its version : All
* device(s) + operating system(s): Windows

### Steps to reproduce
Try to load gitter link or any social platform.

### Expected behaviour
It should load the social site.

Please find screenshot for reference.

![CrossOrigin](https://user-images.githubusercontent.com/26135970/54114150-c281de80-440f-11e9-999e-72c88e9041d9.jpg)

**Comment by moloko** [comment]
In that specific instance, gitter.im is sending an `X-Frame-Options` header set to `deny`. there's no working around that as far as I know - and I wouldn't call it a bug in this plugin.

**Comment by akshay-bhavsar** [comment]
@moloko i had tried with different social media like facebook, instagram, twitter,etc.

**Comment by simondate** [comment]
Hi @akshay-bhavsar , yes most websites send prevent you from accessing them via iFrame. Read this - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

The solution is either to have the server configured to accept being embeded as an iframe or launching the content from the some domain.

For example at King's College London we open the Adapt module from the LMS and then we are linking back to the same LMS for the discussion forum. The discussion forum is the forum they can access from Moodle. We just apply some CSS to make it a bit more "focused".

There are lots of ways to use this extension so I have on purpose kept the description quite vague. I'm gonna close this issue as it doesn't seem to be an actual issue as Matt pointed out.
